### ISSUE TITLE
Clean up I18n translation paths

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#635]
While we're currently only using `en` locale for translations, the directory structure and yaml key paths need to be cleaned up. 

For example (one of _many_ examples that can be cleaned up):

https://github.com/maybe-finance/maybe/blob/5516b03b6ebd18dfce8e905452c80b447c560ffb/config/locales/views/shared/en.yml#L3-L22

In this example, the path of the keys should map to the directory structure so we can benefit from [lazy lookups](https://guides.rubyonrails.org/i18n.html#lazy-lookup) in controllers and views.

## Tasks

- [ ] Make sure translations follow the directory structure of the project
- [ ] Make sure `i18n-tasks` can run all commands (currently it is broken for `i18n-tasks add-missing`
- [ ] ??? (there may be additional cleanup needed)
